services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  app:
    build:
      #context: .
      dockerfile: src/Dockerfile
    depends_on:
      db: 
       condition: service_healthy
    ports:
      - 8000:8000
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      INSTANCE_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      DATA_DIR: /app/data
      LOGS_DIR: /app/logs
      BACKUPS_DIR: /app/backups
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./data:/app/data
      - ./keys:/app/keys
